module.exports = {
  "states" : [
    'Anambra',
    'Enugu',
    'Akwa Ibom',
    'Adamawa',
    'Abia',
    'Bauchi',
    'Bayelsa',
    'Benue',
    'Borno',
    'Cross River',
    'Delta',
    'Ebonyi',
    'Edo',
    'Ekiti',
    'Gombe',
    'Imo',
    'Jigawa',
    'Kaduna',
    'Kano',
    'Katsina',
    'Kebbi',
    'Kogi',
    'Kwara',
    'Lagos',
    'Nasarawa',
    'Niger',
    'Ogun',
    'Ondo',
    'Osun',
    'Oyo',
    'Plateau',
    'Rivers',
    'Sokoto',
    'Taraba',
    'Yobe',
    'Zamfara'
  ],

  "categories" : [
    'Anasthetics', 
    'Analgesics,Anti Inflammatory & Anti Pyretics', 
    'Animal Vaccine Products', 
    'Anti Acids & Ulcer Healer Drugs', 
    'Anti Diabetics ', 
    'Anti  Asthmatics', 
    'Anti Bacterial Agents & Anti Protozal agents', 
    'Anti Biotics', 
    'Anti Caner', 
    'Anti Diarrhoea Drugs & Laxatives', 
    'Antiemetics & Antispasmodic', 
    'Anti Fungals', 
    'Anti Hemorroid Preparations', 
    'Anti Helminitics', 
    'Anti Histamines', 
    'Anti Malrials', 
    'Anti Migraine Drugs', 
    'Anti Muscarinic', 
    'Anti Neoplastic & Immunomodulating Agents', 
    'Anti Psychotic', 
    'Antiseptics,Disinfectants & Mouthwashes', 
    'Anti tussive,Expectorants & Mucolytics', 
    'Antiviral', 
    'Cardiovascular System', 
    'Contraceptives', 
    'Dermatological Preparations', 
    'Parkinson Drugs', 
    'Eye,Ear & Throat Preparations', 
    'Haematinics', 
    'Herbal Products', 
    'Hormones,Synthetics,Substitutes & Thyroid Drugs', 
    'Human Biologicals', 
    'Human Vaccine Products', 
    'Hypnotics,Anxiolities,Anti Convulsants & Anti depressant', 
    'Insecticides', 
    'Oxytocics', 
    'Pesticide Products', 
    'Rubefacients', 
    'Skeletal Muscle Relaxants', 
    'Vaccines & Biologicals', 
    'Veterinary Drugs/Products', 
    'Vitamins & Minerals', 
    'Miscellaneous', 
    'Others'
  ]

};